sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres
  - DB=mysql

gemfile:
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_master.gemfile

rvm:
  - 2.3.1
  - 2.2.7

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
  code_climate:
    repo_token: 7ca9964050acd0a0fbedb864033493bb31c166b170bb034246b714b46419c605

after_success:
  - bundle exec codeclimate-test-reporter
